#!/usr/bin/env python3
"""Export a separate portable OpenAI upload without changing Claude source."""

import argparse
import csv
import importlib.util
import json
from pathlib import Path
import re
import random
import shutil
import sys
import tempfile
from zipfile import ZIP_DEFLATED, ZipFile

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.dont_write_bytecode = True


def export(name: str, output: Path) -> None:
    spec = importlib.util.spec_from_file_location(
        "generator", ROOT / "scripts/generate-plugin-artifacts.py"
    )
    generator = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(generator)
    source = ROOT / "plugins" / name
    metadata = generator.load_yaml(source / "plugin.yaml")
    if metadata["name"] != name:
        raise ValueError("Plugin identity must match its directory")
    if (source / "hooks").exists() or (source / ".app.json").exists():
        raise ValueError("Public uploads cannot include lifecycle hooks or app bindings")
    codex = generator.codex_manifest(source, metadata)
    interface = codex["interface"]
    for key in ("displayName", "shortDescription"):
        if not 0 < len(interface[key]) <= 30:
            raise ValueError(f"{key} must contain 1-30 characters")
    extension = dict(codex.get("extensions", {}).get("com.openai", {}))
    extension["interface"] = interface
    manifest = generator.base_manifest(metadata)
    manifest["description"] = interface["longDescription"]
    manifest["$schema"] = "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json"
    manifest["extensions"] = {"com.openai": extension}
    with tempfile.TemporaryDirectory(prefix="ololand-openai-") as temp:
        package = Path(temp) / name
        package.mkdir()
        for skill in sorted((source / "skills").iterdir()):
            if not skill.is_dir() or not (skill / "SKILL.md").exists():
                continue
            text = (skill / "SKILL.md").read_text()
            front, body = text.split("---\n", 2)[1:]
            fields = yaml.safe_load(front)
            destination = package / "skills" / fields["name"]
            if destination.exists():
                raise ValueError("Duplicate skill name")
            shutil.copytree(skill, destination)
            # Keep provider-specific implementation in the original source.
            body = body.replace("<!-- Generated by scripts/generate-plugin-artifacts.py; do not edit. -->\n", "")
            body = body.replace("# Codex wrapper for /", "# Workflow for /")
            body = body.replace("or the equivalent workflow in Codex", "or the equivalent workflow")
            body = body.replace("Project Atlas Claude memo", "Project Atlas memo")
            body = body.replace("Cowork", "your assistant")
            body = body.replace("Claude", "the assistant")
            if skill.name == "cmd-forensic-screen":
                start = body.find("The PDF includes 7 sections:")
                end = body.find("\n## When the user wants human verification", start)
                if start >= 0 and end >= 0:
                    body = body[:start] + (
                        "Report only the sections and download URL actually returned by the service. "
                        "Do not promise a fixed set of report sections or a completion time. "
                        "Account access and quotas are determined by the service.\n"
                    ) + body[end:]
            # Drop obsolete pricing and latency promises from the upload copy.
            fields["description"] = re.sub(r" The \$99 / 72-hour SLA.*$", "", fields["description"])
            body = re.sub(r"Returns the full screen in 60-90 seconds[^\n]*", "Report only the completion status and findings actually returned by the service.", body)
            body += "\n\n## OpenAI execution requirements\n\n"
            body += (
                "Use the connected MCP server's current tool schemas. Do not invent tool arguments, "
                "job-status endpoints, inputs, or outputs. If a referenced tool is unavailable, "
                "explain the limitation and request the needed connection or data. Invoke writes "
                "only when the user has requested the corresponding action. Do not initiate purchases "
                "or payments. Statistical flags are investigation prompts, not proof of fraud. "
                "An unrun, unsupported, or unavailable procedure is a gap, never a passing result.\n\n"
                "The conversation-level forensic tools and the self-serve PDF report have different "
                "coverage. The current self-serve Full QoE report supports eligible transaction-level "
                "Benford, lapping, and journal-entry tests. It does not currently include Beneish, "
                "EBITDA bridge, full cross-document reconciliation, working-capital normalization, "
                "or revenue-quality deep dives. Do not promise these sections in a PDF or a signed "
                "CPA opinion. Preserve the limits returned by each tool.\n"
            )
            (destination / "SKILL.md").write_text(
                "---\n" + yaml.safe_dump(fields, sort_keys=False).rstrip() + "\n---\n" + body
            )
        if (source / "assets").exists():
            shutil.copytree(source / "assets", package / "assets")
        fixtures = ROOT / "docs" / "openai-review-fixtures"
        if fixtures.is_dir():
            shutil.copytree(fixtures, package / "review-fixtures")
            rng = random.Random(20261002)
            with (package / "review-fixtures/general-ledger.csv").open("w", newline="") as handle:
                writer = csv.writer(handle)
                writer.writerow(["fixture_type", "transaction_id", "date", "account", "amount", "currency", "posting_user"])
                for index in range(1500):
                    amount = round(10 ** rng.uniform(1, 5), 2)
                    if index % 25 == 0:
                        amount = 10000.0
                    writer.writerow([
                        "synthetic", f"JE-{index + 1:05d}",
                        f"2025-{index % 12 + 1:02d}-{index % 28 + 1:02d}",
                        "4000" if index % 2 == 0 else "5000", amount, "USD", "review_fixture",
                    ])
        mcp = json.loads((source / ".mcp.json").read_text())
        mcp["$schema"] = "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json"
        for server in mcp["mcpServers"].values():
            if not server["url"].startswith("https://"):
                raise ValueError("Public MCP endpoint must use HTTPS")
            server["type"] = "streamable-http"
        (package / "mcp.json").write_text(json.dumps(mcp, indent=2) + "\n")
        (package / "plugin.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")
        shutil.copy2(ROOT / "LICENSE", package / "LICENSE")
        for key in ("logo", "composerIcon"):
            asset = package / interface[key]
            if not asset.is_file() or not asset.resolve().is_relative_to(package.resolve()):
                raise ValueError(f"Missing or unsafe {key}")
        output.parent.mkdir(parents=True, exist_ok=True)
        with ZipFile(output, "w", ZIP_DEFLATED) as archive:
            for path in sorted(package.rglob("*")):
                if path.is_symlink():
                    raise ValueError("Symlinks are not allowed")
                if path.is_file():
                    archive.write(path, path.relative_to(package.parent))
    print(output.resolve())


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("name")
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", args.name):
        parser.error("Use a kebab-case plugin name")
    export(args.name, args.output)
