#!/usr/bin/env python3
"""Export a separate portable OpenAI upload without changing Claude source."""

import argparse
import importlib.util
import json
from pathlib import Path
import re
import shutil
import sys
import tempfile
from zipfile import ZIP_DEFLATED, ZipFile

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.dont_write_bytecode = True


def neutral_text(text: str) -> str:
    """Normalize complete provider phrases before their component words."""
    text = text.replace("Project Atlas Claude memo", "Project Atlas memo")
    text = text.replace("Claude Cowork", "your assistant")
    text = text.replace("Cowork", "your assistant")
    text = text.replace("Claude", "the assistant")
    return re.sub(r"\bmcp__ololand__([a-zA-Z0-9_]+)\b", r"\1", text)


def export(name: str, output: Path) -> None:
    spec = importlib.util.spec_from_file_location(
        "generator", ROOT / "scripts/generate-plugin-artifacts.py"
    )
    generator = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(generator)
    source = ROOT / "plugins" / name
    metadata = generator.load_yaml(source / "plugin.yaml")
    if metadata["name"] != name:
        raise ValueError("Plugin identity must match its directory")
    if (source / "hooks").exists() or (source / ".app.json").exists():
        raise ValueError("Public uploads cannot include lifecycle hooks or app bindings")
    codex = generator.codex_manifest(source, metadata)
    interface = codex["interface"]
    for key in ("displayName", "shortDescription"):
        if not 0 < len(interface[key]) <= 30:
            raise ValueError(f"{key} must contain 1-30 characters")
    extension = dict(codex.get("extensions", {}).get("com.openai", {}))
    extension["interface"] = interface
    manifest = generator.base_manifest(metadata)
    manifest["description"] = interface["longDescription"]
    manifest["$schema"] = "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json"
    manifest["extensions"] = {"com.openai": extension}
    mcp = json.loads((source / ".mcp.json").read_text())
    mcp["$schema"] = "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json"
    dependencies = []
    for server_name, server in mcp["mcpServers"].items():
        if not server["url"].startswith("https://"):
            raise ValueError("Public MCP endpoint must use HTTPS")
        server["type"] = "streamable-http"
        dependencies.append({
            "type": "mcp", "value": server_name,
            "description": f"Connected {metadata['displayName']} tools",
            "transport": "streamable_http", "url": server["url"],
        })
    skills = []
    references = {}
    for skill in sorted((source / "skills").iterdir()):
        if not skill.is_dir() or not (skill / "SKILL.md").exists():
            continue
        text = (skill / "SKILL.md").read_text()
        front, body = text.split("---\n", 2)[1:]
        fields = yaml.safe_load(front)
        skills.append((skill, fields, body))
        if skill.name.startswith("cmd-"):
            references[f"/{skill.name}"] = fields["name"]
            references[f"/{skill.name.removeprefix('cmd-')}"] = fields["name"]
    command_pattern = (
        re.compile(r"(?<![\w/])(?:" + "|".join(
            re.escape(key) for key in sorted(references, key=len, reverse=True)
        ) + r")(?![\w-])")
        if references else None
    )
    with tempfile.TemporaryDirectory(prefix="ololand-openai-") as temp:
        package = Path(temp) / name
        package.mkdir()
        for skill, fields, body in skills:
            destination = package / "skills" / fields["name"]
            if destination.exists():
                raise ValueError("Duplicate skill name")
            shutil.copytree(skill, destination)
            # Keep provider-specific implementation in the original source.
            body = body.replace("<!-- Generated by scripts/generate-plugin-artifacts.py; do not edit. -->\n", "")
            body = body.replace("# Codex wrapper for /", "# Workflow for /")
            body = body.replace("or the equivalent workflow in Codex", "or the equivalent workflow")
            body = neutral_text(body)
            fields["description"] = neutral_text(fields["description"])
            if name == "ololand-forensic-qoe" and skill.name == "forensic-qoe":
                body = body.replace(
                    "This output shape is what the `/cmd-forensic-screen` and `/cmd-dd-analyze` commands aggregate into a Pre-LOI Screen and full Forensic QoE respectively.",
                    "Use the packaged `ololand-forensic-qoe-forensic-screen` workflow to summarize only results actually returned by the service. This upload does not include the general due-diligence workflow; request that separate plugin if needed.",
                )
            if command_pattern:
                body = command_pattern.sub(lambda match: references[match.group()], body)
                fields["description"] = command_pattern.sub(
                    lambda match: references[match.group()], fields["description"]
                )
            if re.search(r"/cmd-[a-z0-9-]+", body + fields["description"]):
                raise ValueError(f"Unpackaged command reference in {skill.name}")
            if skill.name == "cmd-forensic-screen":
                start = body.find("## When the user wants the PDF deliverable")
                end = body.find("\n## When the user wants human verification", start)
                if start < 0 or end < 0:
                    raise ValueError("PDF workflow boundary missing")
                body = body[:start] + (
                    "## When the user wants the PDF deliverable\n\n"
                    "PDF generation is a separate metered action. The service's published MCP "
                    "pricing identifies `generate_forensic_screen_pdf` as **50 service credits**. "
                    "Confirm the current cost, available quota, and account entitlement in OloLand "
                    "before execution; if they cannot be verified, stop and request that verification.\n\n"
                    "1. Check whether `generate_forensic_screen_pdf` is actually available to the "
                    "connected account. If unavailable, explain the access limitation.\n"
                    "2. Disclose the verified cost and obtain the user's explicit confirmation "
                    "to generate the report and consume those service credits. A request for a "
                    "PDF alone does not confirm an undisclosed charge. Do not initiate a purchase "
                    "or payment to obtain credits.\n"
                    "3. Only after that confirmation, invoke the tool using its current schema "
                    "and the resolved deal ID. Use a status tool only if the connected server "
                    "actually exposes it and the result supplies the required job identifier.\n"
                    "4. Report only the status, sections, and download URL returned by the service. "
                    "Do not promise fixed report sections or completion timing.\n"
                ) + body[end:]
            # Drop obsolete pricing and latency promises from the upload copy.
            fields["description"] = re.sub(r" The \$99 / 72-hour SLA.*$", "", fields["description"])
            body = re.sub(r"Returns the full screen in 60-90 seconds[^\n]*", "Report only the completion status and findings actually returned by the service.", body)
            body += "\n\n## OpenAI execution requirements\n\n"
            body += (
                "Use the connected MCP server's current tool schemas. Do not invent tool arguments, "
                "job-status endpoints, inputs, or outputs. If a referenced tool is unavailable, "
                "explain the limitation and request the needed connection or data. Invoke writes "
                "only when the user has requested the corresponding action. Do not initiate purchases "
                "or payments. Statistical flags are investigation prompts, not proof of fraud. "
                "An unrun, unsupported, or unavailable procedure is a gap, never a passing result.\n\n"
                "The conversation-level forensic tools and the self-serve PDF report have different "
                "coverage. The current self-serve Full QoE report supports eligible transaction-level "
                "Benford, lapping, and journal-entry tests. It does not currently include Beneish, "
                "EBITDA bridge, full cross-document reconciliation, working-capital normalization, "
                "or revenue-quality deep dives. Do not promise these sections in a PDF or a signed "
                "CPA opinion. Preserve the limits returned by each tool.\n"
            )
            (destination / "SKILL.md").write_text(
                "---\n" + yaml.safe_dump(fields, sort_keys=False).rstrip() + "\n---\n" + body
            )
            agents = destination / "agents"
            agents.mkdir(exist_ok=True)
            (agents / "openai.yaml").write_text(yaml.safe_dump({
                "interface": {
                    "display_name": fields["name"].removeprefix(name + "-").replace("-", " ").title(),
                    "short_description": fields["description"][:200],
                },
                "dependencies": {"tools": dependencies},
            }, sort_keys=False))
        if (source / "assets").exists():
            shutil.copytree(source / "assets", package / "assets")
        fixtures = ROOT / "docs" / "openai-review-fixtures"
        if fixtures.is_dir():
            shutil.copytree(fixtures, package / "review-fixtures")
        (package / "mcp.json").write_text(json.dumps(mcp, indent=2) + "\n")
        (package / "plugin.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")
        shutil.copy2(ROOT / "LICENSE", package / "LICENSE")
        for key in ("logo", "composerIcon"):
            asset = package / interface[key]
            if not asset.is_file() or not asset.resolve().is_relative_to(package.resolve()):
                raise ValueError(f"Missing or unsafe {key}")
        output.parent.mkdir(parents=True, exist_ok=True)
        with ZipFile(output, "w", ZIP_DEFLATED) as archive:
            for path in sorted(package.rglob("*")):
                if path.is_symlink():
                    raise ValueError("Symlinks are not allowed")
                if path.is_file():
                    archive.write(path, path.relative_to(package.parent))
    print(output.resolve())


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("name")
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", args.name):
        parser.error("Use a kebab-case plugin name")
    export(args.name, args.output)
