#!/usr/bin/env python3
"""Generate Claude and Codex plugin artifacts from canonical YAML metadata."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError as exc:
    raise SystemExit(
        "PyYAML is required. Run: python3 -m pip install -r scripts/requirements.txt"
    ) from exc


REPO_ROOT = Path(__file__).resolve().parents[1]
SEMVER_RE = re.compile(r"^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$")
GENERATED_SKILL_MARKER = "Generated by scripts/generate-plugin-artifacts.py; do not edit."


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return data


def json_text(data: dict[str, Any]) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def kebab(value: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "-", value.strip().lower())
    return re.sub(r"-+", "-", normalized).strip("-")


def title_category(value: str) -> str:
    parts = re.split(r"[-_\s]+", value.strip())
    return " ".join(part[:1].upper() + part[1:] for part in parts if part)


def claude_category(value: str) -> str:
    return kebab(value)


def plugin_dir(plugin_name: str) -> Path:
    return REPO_ROOT / "plugins" / plugin_name


def plugin_source(plugin_name: str) -> str:
    return f"./plugins/{plugin_name}"


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def base_manifest(plugin: dict[str, Any]) -> dict[str, Any]:
    author = plugin.get(
        "author",
        {
            "name": "OloLand",
            "email": "support@ololand.ai",
            "url": "https://ololand.ai",
        },
    )
    return {
        "name": plugin["name"],
        "version": str(plugin["version"]),
        "description": plugin["description"],
        "author": author,
        "homepage": plugin["homepage"],
        "repository": plugin["repository"],
        "license": plugin["license"],
        "keywords": plugin.get("keywords", []),
    }


def codex_components(root: Path, plugin: dict[str, Any]) -> dict[str, str]:
    configured = plugin.get("components", {}).get("codex", {})
    components: dict[str, str] = {}

    if (root / "skills").is_dir() and list((root / "skills").glob("*/SKILL.md")):
        components["skills"] = "./skills/"
    if (root / "hooks" / "hooks.json").is_file():
        components["hooks"] = "./hooks/hooks.json"
    if (root / ".mcp.json").is_file():
        components["mcpServers"] = "./.mcp.json"
    if (root / ".app.json").is_file():
        components["apps"] = "./.app.json"

    for key in ("skills", "hooks", "mcpServers", "apps"):
        if configured.get(key):
            components[key] = configured[key]

    return components


def codex_manifest(root: Path, plugin: dict[str, Any]) -> dict[str, Any]:
    manifest = base_manifest(plugin)
    manifest.update(codex_components(root, plugin))

    interface = plugin.get("interface", {})
    manifest["interface"] = {
        "displayName": plugin.get("displayName", plugin["name"]),
        "shortDescription": plugin.get("shortDescription", plugin["description"]),
        "longDescription": plugin.get("longDescription", plugin["description"]),
        "developerName": plugin.get("developerName", "OloLand"),
        "category": title_category(plugin["category"]),
        "capabilities": plugin.get("capabilities", ["Read", "Interactive"]),
        "websiteURL": interface.get("websiteURL", plugin["homepage"]),
        "privacyPolicyURL": interface.get("privacyPolicyURL", "https://ololand.ai/privacy"),
        "termsOfServiceURL": interface.get("termsOfServiceURL", "https://ololand.ai/terms"),
        "defaultPrompt": plugin.get("defaultPrompt", [])[:3],
        "brandColor": interface.get("brandColor", "#0F766E"),
        "screenshots": interface.get("screenshots", []),
    }
    if interface.get("composerIcon"):
        manifest["interface"]["composerIcon"] = interface["composerIcon"]
    if interface.get("logo"):
        manifest["interface"]["logo"] = interface["logo"]

    return manifest


def claude_manifest(plugin: dict[str, Any]) -> dict[str, Any]:
    manifest = base_manifest(plugin)
    extra = plugin.get("claude", {}).get("extraManifestFields", {})
    manifest.update(extra)
    return manifest


def build_claude_marketplace(
    marketplace: dict[str, Any], plugins: list[dict[str, Any]]
) -> dict[str, Any]:
    return {
        "name": marketplace["name"],
        "owner": marketplace.get("owner", {}),
        "metadata": {
            "description": marketplace["description"],
        },
        "plugins": [
            {
                "name": plugin["name"],
                "version": str(plugin["version"]),
                "source": plugin_source(plugin["name"]),
                "category": claude_category(plugin["category"]),
                "description": plugin.get("marketplaceDescription", plugin["description"]),
            }
            for plugin in plugins
            if plugin.get("targets", {}).get("claude", True)
        ],
    }


def build_codex_marketplace(
    marketplace: dict[str, Any], plugins: list[dict[str, Any]]
) -> dict[str, Any]:
    default_policy = marketplace.get("codex", {}).get("policy", {})
    installation = default_policy.get("installation", "AVAILABLE")
    authentication = default_policy.get("authentication", "ON_INSTALL")

    return {
        "name": marketplace["name"],
        "interface": {
            "displayName": marketplace.get("displayName", marketplace["name"]),
        },
        "plugins": [
            {
                "name": plugin["name"],
                "source": {
                    "source": "local",
                    "path": plugin_source(plugin["name"]),
                },
                "policy": {
                    "installation": plugin.get("codex", {}).get(
                        "installation", installation
                    ),
                    "authentication": plugin.get("codex", {}).get(
                        "authentication", authentication
                    ),
                },
                "category": title_category(plugin["category"]),
            }
            for plugin in plugins
            if plugin.get("targets", {}).get("codex", True)
        ],
    }


def validate(marketplace: dict[str, Any], plugins: list[dict[str, Any]]) -> None:
    names = marketplace.get("plugins")
    require(isinstance(names, list) and names, "marketplace.yaml must list plugins")

    seen: set[str] = set()
    for plugin in plugins:
        name = plugin["name"]
        root = plugin_dir(name)
        require(name == kebab(name), f"{name}: plugin name must be kebab-case")
        require(name not in seen, f"{name}: duplicate plugin entry")
        seen.add(name)
        require(root.is_dir(), f"{name}: missing plugin directory at {root}")
        require(
            SEMVER_RE.match(str(plugin["version"])) is not None,
            f"{name}: version must be semver",
        )
        require(plugin.get("description"), f"{name}: description is required")
        require(plugin.get("category"), f"{name}: category is required")

    missing = set(names) - seen
    extra = seen - set(names)
    require(not missing, f"marketplace.yaml references missing plugins: {sorted(missing)}")
    require(not extra, f"plugin.yaml exists for unlisted plugins: {sorted(extra)}")


def write_or_check(path: Path, content: str, check: bool, drift: list[Path]) -> None:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            drift.append(path)
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def parse_command_markdown(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return "", text

    _, frontmatter, body = text.split("---\n", 2)
    metadata = yaml.safe_load(frontmatter) or {}
    description = metadata.get("description", "") if isinstance(metadata, dict) else ""
    return str(description), body.lstrip()


def command_skill_text(plugin: dict[str, Any], command_path: Path) -> str:
    command_name = command_path.stem
    description, body = parse_command_markdown(command_path)
    skill_name = f"{plugin['name']}-{command_name}"
    skill_description = (
        f"Use when the user asks to run the OloLand /{command_name} workflow. "
        f"{description}"
    ).strip()

    return "\n".join(
        [
            "---",
            f"name: {skill_name}",
            f"description: {json.dumps(skill_description, ensure_ascii=False)}",
            "---",
            "",
            f"<!-- {GENERATED_SKILL_MARKER} -->",
            "",
            f"# Codex wrapper for /{command_name}",
            "",
            f"Follow the OloLand command instructions below when the user asks for `/{command_name}` or the equivalent workflow in Codex.",
            "",
            body,
        ]
    ).rstrip() + "\n"


def generated_command_skill_paths(root: Path) -> set[Path]:
    paths: set[Path] = set()
    for skill_md in (root / "skills").glob("*/SKILL.md"):
        try:
            if GENERATED_SKILL_MARKER in skill_md.read_text(encoding="utf-8"):
                paths.add(skill_md)
        except FileNotFoundError:
            continue
    return paths


def write_or_check_command_skills(
    root: Path, plugin: dict[str, Any], check: bool, drift: list[Path]
) -> None:
    if not plugin.get("codex", {}).get("generateCommandSkills", True):
        return

    commands_dir = root / "commands"
    if not commands_dir.is_dir():
        return

    expected: set[Path] = set()
    for command_path in sorted(commands_dir.glob("*.md")):
        target = root / "skills" / f"cmd-{command_path.stem}" / "SKILL.md"
        if target.exists() and GENERATED_SKILL_MARKER not in target.read_text(
            encoding="utf-8"
        ):
            raise ValueError(
                f"{plugin['name']}: refusing to overwrite hand-written skill {target}"
            )
        expected.add(target)
        write_or_check(target, command_skill_text(plugin, command_path), check, drift)

    stale = generated_command_skill_paths(root) - expected
    if check:
        drift.extend(sorted(stale))
        return

    for path in stale:
        path.unlink()
        try:
            path.parent.rmdir()
        except OSError:
            pass


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated artifacts are missing or stale",
    )
    args = parser.parse_args()

    marketplace = load_yaml(REPO_ROOT / "marketplace.yaml")
    plugin_names = marketplace["plugins"]
    plugins = [load_yaml(plugin_dir(name) / "plugin.yaml") for name in plugin_names]
    validate(marketplace, plugins)

    drift: list[Path] = []
    for plugin in plugins:
        root = plugin_dir(plugin["name"])
        if plugin.get("targets", {}).get("codex", True):
            write_or_check_command_skills(root, plugin, args.check, drift)
        if plugin.get("targets", {}).get("claude", True):
            write_or_check(
                root / ".claude-plugin" / "plugin.json",
                json_text(claude_manifest(plugin)),
                args.check,
                drift,
            )
        if plugin.get("targets", {}).get("codex", True):
            write_or_check(
                root / ".codex-plugin" / "plugin.json",
                json_text(codex_manifest(root, plugin)),
                args.check,
                drift,
            )

    write_or_check(
        REPO_ROOT / ".claude-plugin" / "marketplace.json",
        json_text(build_claude_marketplace(marketplace, plugins)),
        args.check,
        drift,
    )
    write_or_check(
        REPO_ROOT / ".agents" / "plugins" / "marketplace.json",
        json_text(build_codex_marketplace(marketplace, plugins)),
        args.check,
        drift,
    )

    if drift:
        print("Generated plugin artifacts are stale:", file=sys.stderr)
        for path in drift:
            print(f"  {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        print(
            "Run `python3 scripts/generate-plugin-artifacts.py` and commit the changes.",
            file=sys.stderr,
        )
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
